version: '2.4'

services:
  petclinic:
    image: ghcr.io/observabilitystack/spring-petclinic:latest
    mem_limit: 320m
    cpus: 1
    restart: unless-stopped
    environment:
      - spring_profiles_active=postgres
      - POSTGRES_URL=jdbc:postgresql://postgresql/petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_PASS=petclinic
    labels:
      - traefik.enable=true
      - traefik.http.routers.petclinic.rule=Host(`petclinic.${HOSTNAME}.${DOMAIN_NAME}`)
      - traefik.http.routers.petclinic.service=petclinic
      - traefik.http.services.petclinic.loadbalancer.server.port=8080
    volumes:
      - ./../java-flight-recorder:/tmp/jfr
    depends_on:
      - postgresql

  postgresql:
    image: postgres:15
    mem_limit: 64m
    cpus: 0.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic

networks:
  default:
    name: o11ystack
    external: true
