route:
  group_wait: 15s
  group_interval: 30s
  repeat_interval: 24h
  receiver: default
  routes:
      # The default receiver is empty and does nothing.
      # BUT the alert groups panel in Grafana is grouped
      # by it's grouping specification
    - receiver: default
      group_by: [ severity ]
      continue: true

receivers:
  - name: default
