version: '2.4'

services:
  grafana_agent:
    image: grafana/agent:latest
    command: |
      -config.file=/etc/agent/agent.yaml -config.expand-env
    environment:
      - GRAFANA_TEMPO_USERNAME=${GRAFANA_TEMPO_USERNAME}
      - GRAFANA_API_KEY=${GRAFANA_API_KEY}
    volumes:
      - ./rootfs/etc/agent:/etc/agent

networks:
  default:
    name: o11ystack
    external: true
