groups:
- name: gateway
  rules:

  - alert: SpringBootHighNumberOf5xx
    expr: rate(http_server_requests_seconds_count{status=~"5..",uri!~"/actuator/.*"}[1m]) * 60 > 5
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: The service {{ $labels.service }} has a high number of 503 responses on customer facing endpoints
      description: Please check the application logs
