# @see https://awesome-prometheus-alerts.grep.to/alertmanager
#
groups:
- name: traefik
  rules:

  # Traefik v2
  - alert: TraefikDown
    expr: up{job="traefik"} == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: Traefik http server down (instance {{ $labels.instance }})
      description: "The Traefik container cannot be reached and might be down."

  - alert: TraefikServiceDown
    expr: count(traefik_service_server_up) by (stage, service) == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Traefik service down (instance {{ $labels.instance }})
      description: "All Traefik services are down"

  - alert: TraefikHighHttp4xxErrorRateService
    expr: sum(rate(traefik_service_requests_total{code=~"4(0|1).*"}[3m])) by (stage,service) / sum(rate(traefik_service_requests_total[3m])) by (stage,service) * 100 > 5
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Traefik high HTTP 4xx error rate service (instance {{ $labels.instance }})
      description: "Traefik service 4xx error rate is above 5%"

  - alert: TraefikHighHttp5xxErrorRateService
    expr: sum(rate(traefik_service_requests_total{code=~"5.*"}[3m])) by (stage,service) / sum(rate(traefik_service_requests_total[3m])) by (stage,service) * 100 > 5
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Traefik high HTTP 5xx error rate service (instance {{ $labels.instance }})
      description: "Traefik service 5xx error rate is above 5%"
